### PR TITLE
Feat/filter

### PR DESCRIPTION
**Pull request by Aditi0505**
# Change Logs:

## Description:
- Added Multiple Filter Functionality -
1. By price
2. By Category

- Added Sort Functionality
- Added Clear Filter Functionality
## Screenshots
image
image

## Preview Link
https://deploy-preview-3--theredclosetapp.netlify.app/

### CODE REVIEW

**Review by anupkgurung — APPROVED** [review]
Nice use of function in filters.
Component breakdown  is good.
Suggestion (optional) wherever you are using constant values like price you can also move all such constant values to a constant file  and use them directly.

**Review by rohanmathur91 — APPROVED** [review]
- Nice use of reusable components
 - Good use of barrel exports
 - One suggestion, add comments to your utils functions

**Comment by Aditi0505** [comment]
> Nice use of function in filters. Component breakdown is good. Suggestion (optional) wherever you are using constant values like price you can also move all such constant values to a constant file and use them directly.

Thank you for sharing! I will do this as refactoring after done with main functionalities.

**Comment by Aditi0505** [comment]
> * Nice use of reusable components
> * Good use of barrel exports
> * One suggestion, add comments to your utils functions

Thank you for sharing! I will do this as refactoring after done with main functionalities.

**Pull request merged**
